server:
  port: 8082

spring:
  application:
    name: patient-service

  datasource:
    # localhost:5432 diyerek Docker'ın dışarıya açtığı porta bağlanıyoruz kanka
    url: jdbc:postgresql://localhost:5432/medix_patient_db
    username: patient_user
    password: patient_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.devberatzengin.patientservice: INFO
  pattern:
    # 🌈 SİHİRLİ DOKUNUŞ: %clr(...) fonksiyonları ile konsolu jilet gibi renklendiriyoruz kanka
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr([%thread]){magenta} %clr(%-5level){yellow} %clr(%logger{36}){cyan} - %clr(%msg%n){gray}"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/patient-service.log

eureka:
  client:
    enabled: false

springdoc:
  swagger-ui:
    # Swagger paneline tarayıcıdan hangi adresten gireceğimizi belirliyoruz kanka
    path: /swagger-ui.html
    # Endpoint'leri Controller bazlı sıralasın diye
    operationsSorter: alpha
  api-docs:
    path: /v3/api-docs
  packages-to-scan: org.devberatzengin.controller
